package com.example.databinding;


import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.example.databinding.databinding.FragmentViewProductBinding;
import com.example.databinding.models.Product;
import com.example.databinding.models.ProductViewModel;
import com.example.databinding.util.Products;

public class ViewProductFragment extends Fragment{
    private static final String TAG = "ViewProductFragment";

    // Data binding
    FragmentViewProductBinding mBinding;
    private Product mProduct;

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bundle bundle = this.getArguments();
        if (bundle != null){
            mProduct = bundle.getParcelable("intent_product");
        }
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        mBinding = FragmentViewProductBinding.inflate(inflater);
        mBinding.setIMainActivity((IMainActivity)getActivity());

        Products products = new Products();
        //the method setProduct auto generated by the binding library based on the value we give to our layout like below
        //           <variable
        //            name="product"
        //            type="com.example.databinding.models.Product"/>

        ProductViewModel productView = new ProductViewModel();
        productView.setProduct(mProduct);
        productView.setQuantity(1);
        mBinding.setProductView(productView);


        return mBinding.getRoot();
    }
}
